### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by kingmaj0r** [andrius4669/zeromod-sauerbraten#13]
# I need help!

> hi, I want to host a sauerbraten server with zero mod but for some reason, I can't get it working do you think you can help me?

> thx, have a nice day.

**Comment by andrius4669** [comment]
did you read https://github.com/andrius4669/zeromod-sauerbraten/blob/master/INSTALL

**Comment by kingmaj0r** [comment]
yes, but I'm having trouble please help me im on ubuntu

**Comment by kingmaj0r** [comment]
I've ran every command on it but it's, not the same as (RUGBY ICTF)

**Comment by andrius4669** [comment]
we don't do rugby mode yet

**Comment by kingmaj0r** [comment]
oh okay.

**Comment by kingmaj0r** [comment]
how do we start the server after we install it like what's the command?

**Comment by andrius4669** [comment]
`bin_unix/native_server` should work after `make server_install`.
you could use systemd user units or daemontools or tmux session to keep it up

**Comment by andrius4669** [comment]
ah yeah, `make server_install` is in src dir while `bin_unix/native_server` is in main repo folder
