### ISSUE TITLE
Source code seems outdated

### ISSUE THREAD

**Issue by 2-bithacker** [andrius4669/zeromod-sauerbraten#14]
I followed the instructions exactly, but when building, I got lots of errors.  I could very easily build the stock client on my pc, but when I tries to do it with the new sourcecode here, it didn't work at all.

**Comment by Calinou** [comment]
@2-bithacker Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by 2-bithacker** [comment]
I had to run `chmod +x ~/sauerbraten/src/enet/check_cflags.sh`  That fixed the problem.
