### ISSUE TITLE
Heyy zero

### ISSUE THREAD

**Issue by DragonSlayer87** [andrius4669/zeromod-sauerbraten#8]
Ure server mod doesnt work on win 64 it says it doesntbfikd sauerserver. exe and alot of dll files. Can u make exe file included so its easier?

**Comment by DragonSlayer87** [comment]
On the pther zeromod not this one

**Comment by DragonSlayer87** [comment]
U got like 10 zeromods which one are you sure will work on windows 64bit.? Alot of other mods got exe file included can u add that?
Thx FragGoD

**Comment by andrius4669** [comment]
you need to compile it.

**Comment by Croydon** [comment]
Maybe you could provide sometimes a release with binaries for non-technical people :)

**Comment by DragonSlayer87** [comment]
Hey zero and other non technical guys like me...
If ure on windows and u get some errors try to put in sauer_server.exe file in bin 64 and it will work. 
Issue closed.

**Comment by andrius4669** [comment]
you'll be using 32-bit binary but if it works for you it's fine I guess...

**Comment by andrius4669** [comment]
regarding support of compiled bins, I no longer develop nor support old zeromod repository.
it's there just so I can look at my old code for nostalgia.
and for zeromod-sauerbraten repository, putting them into git tree doesn't seem like good idea as I'd need to keep them updated with latest commits (and I really not going to remake windows builds at each commit).
something like nighty hosted outside of git would be viable (and I think I even had it set up at one point, but when I moved to other VPS I just didn't bother at redoing that setup again), but I don't know if it's worth bothering, as any serious server hoster I've seen hosts stuff on unix-ish platforms.

**Comment by Croydon** [comment]
@andrius4669 You are on GitHub, use GitHub Releases. That is what I was talking about :)
https://github.com/andrius4669/zeromod-sauerbraten/releases

**Comment by andrius4669** [comment]
@Croydon tagging releases would be manual work, wouldn't it

**Comment by Croydon** [comment]
Of course it would be work to create a tag, a release, compile it, zip it and uploading it to the release. But it would nullify the bins in the repo problem.

**Comment by andrius4669** [comment]
...not worth it

**Comment by deathstar** [comment]
I don't include binaries for my mod either because it's simply not worth it. There isn't a big enough audience looking to download said binaries. Also... to make it fair you would have to make a bunch of different versions of the binaries to make it compatible everywhere. If you're looking to host a server, downloading a compiler isn't more difficult than forwarding ports.
